### PR TITLE
Fix send message to chatwork

### PR DESCRIPTION
**Pull request by hungnh103**

### CODE REVIEW

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
closed

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
merged

**Comment by dieunb** [comment]
merged

**Pull request merged**
